import type { Metadata } from "next";
import localFont from "next/font/local";
import Navigation from "@/components/Navigation";
import "./globals.css";

const fontSans = localFont({
  src: "./fonts/Satoshi.woff2",
  variable: "--font-sans",
  weight: "500",
});

const fontHeadings = localFont({
  src: "./fonts/CabinetGrotesk.woff2",
  variable: "--font-heading",
});

export const metadata: Metadata = {
  title: "GizenGraphics",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${fontSans.variable} ${fontHeadings.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header>
          <Navigation />
        </header>

        {children}
      </body>
    </html>
  );
}
